[package]
name = "craft-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "craft"
path = "src/main.rs"

[dependencies]
craft-core = { path = "../craft-core" }
craft-lsp = { path = "../craft-lsp" }
craft-memory = { path = "../craft-memory" }

[lints]
workspace = true
