[package]
name = "craft-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
craft-manifest = { path = "../craft-manifest" }
rusqlite = { version = "0.32", features = ["bundled"] }

[lints]
workspace = true
